name: api testing

on:
  schedule:
    - cron:  '30 11 * * *'
jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout my repo
      uses: actions/checkout@v3
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pytest requests
    - name: Test with pytest
      run: pytest api_tests/

